#ifndef CONSTANTES_H
#define CONSTANTES_H

#ifndef NULL
#define NULL 0
#endif /* NULL*/

enum TipoCasillero {
	VACIO,
	TESORO,
	ESPIA,
	INACTIVO,
	BLINDADO,
	MINA,
	PARTIDO,
	DESTRUIDO
};

enum TipoCarta {
	BLINDAR,
	REVELAR,
	PARTIRTESORO,
	TRACKEAR,
	ROBARCARTA,
	DUPLICARTURNO
};

enum Perspectiva {
	XY,
	XZ,
	YZ
};

enum TipoCambio {
	ELIMINACION,
	CARTAROBADA,
	TESOROPERDIDO,
	ESPIAPERDIDO,
	MINAPERDIDA,
	BLINDAJEPERDIDO,
	PARTIDOPERDIDO,
	ROBOINICIADO,
	ROBOFINALIZADO,
	ROBOINTERRUMPIDO
};

/* DIMENSIONES DEL TABLERO */
#define CANTIDAD_DIMENSIONES 3

/* MINIMO_DIMENSION NO PUEDE SER MENOR A 5, POR RESTRICCIONES DE PLANO.H */
#define MINIMO_DIMENSION 5
#define MAXIMO_DIMENSION 15

/* TAMAÑO DEL PLANO, DEBE SER 5x5 POR RESTRICCIONES IMPUESTAS */
#define DIMENSION_PLANO 5

/* MINIMO_JUGADORES NO PUEDE SER MENOR A 2 */
#define MINIMO_JUGADORES 2
#define MAXIMO_JUGADORES 10

/* TESOROS POR JUGADOR */
#define MINIMO_TESOROS 1
#define MAXIMO_TESOROS 5

/* RONDAS DE DURACION PARA INACTIVIDAD Y BLINDAJE */
#define INACTIVIDAD_POR_ESPIA 2
#define INACTIVIDAD_POR_MINA 2
#define DURACION_BLINDAJE 2

/* CANTIDAD DE TIPOS DE CARTAS DISPONIBLES */
#define CANTIDAD_CARTAS 6

/* IDJUGADOR DE LOS CASILLEROS QUE NO CORRESPONDEN A UN JUGADOR ACTIVO */
#define ID_GLOBAL 0

/* CONFIGURACION PARA INTERFAZ EN CONSOLA */
#define ANCHO_CONSOLA 100
#define ESPACIADO_SIMPLE 1
#define ESPACIADO_NOTIFICACION 2
#define ESPACIADO_TITULO 3

#endif
